### PR TITLE
Remove lxml dependency

### PR DESCRIPTION
**Pull request by tilmanginzel**
Hi @trietsch, would be cool if you can review this one.

Changes:

- Remove lxml dependency to parse list of Bluetooth devices
- Update `blueutil` which has support for json output
- This unfortunately also removes the battery percentage feature, but it's a trade-off I would be willing to make
- Reduce workflow size from 9.5 MB to 747 KB (!)
- I have the feeling that the device list is shown much faster now after typing `blt` 

I bumped the version to 0.8.0 in case https://github.com/tilmanginzel/alfred-bluetooth-workflow/pull/13 gets merged first.

### CODE REVIEW

**Comment by tilmanginzel** [comment]
Version to test: [Bluetooth Connector.alfredworkflow.zip](https://github.com/tilmanginzel/alfred-bluetooth-workflow/files/3827474/Bluetooth.Connector.alfredworkflow.zip)

Note: this does not contain the notification fix from #13.

**Comment by trietsch** [comment]
Looks good! Pretty nice that you've already answered possible questions that I could have had while reviewing.
I agree on the tradeoff by the way, though `blueutil` had support for percentage in previous versions? Would you like to merge #13 first or this one first?

**Comment by trietsch** [comment]
Btw, don't forget to remove the remaining `__init__.pyc` file in the `lxml` dir.

**Review by trietsch — APPROVED** [review]

**Comment by tilmanginzel** [comment]
Thanks for the quick review!

> though blueutil had support for percentage in previous versions?

No it did not. I previously parsed the output of `system_profiler SPBluetoothDataType -xml`, which contained battery percentage information. `blueutil` is using the [IOBluetooth](https://developer.apple.com/documentation/iobluetooth) api, which apparently does not show this information (but I haven't checked in detail, just that blueutil is not exposing it).

> Would you like to merge #13 first or this one first?

Yup, I will merge both first thing in the morning tomorrow. :)

> Btw, don't forget to remove the remaining __init__.pyc file in the lxml dir.

Ah, good point! I thought I removed the whole directory. Will keep an eye on it when exporting a version for the release.

**Comment by trietsch** [comment]
Cool, sounds good!
On the feature of getting battery percentage, we may be able to use IO registry. Did some research and found [this](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/battery/internal.m#L490) in Hammerspoon, and [this](https://apple.stackexchange.com/questions/215256/check-the-battery-level-of-connected-bluetooth-headphones-from-the-command-line) on Apple StackExchange.

**Comment by tilmanginzel** [comment]
I just merged both pull requests and published them under version [0.7.0](https://github.com/tilmanginzel/alfred-bluetooth-workflow/releases).

Thanks for checking on the battery percentage stuff. I think we can keep it in mind for future releases. :)

**Pull request merged**
