### PR TITLE
Added @trietsch to license, added version file

### PR DESCRIPTION
**Pull request by trietsch**
@tilmanginzel, I've added the version file, and updated the license. PR might be overkill, though it's better than pushing to master directly :)

### CODE REVIEW

**Comment by tilmanginzel** [comment]
I agree. Having small merge requests won't hurt I guess. I have "duplicated" the license also in the readme, so please add it there too. We can merge it afterwards. :)

**Review by tilmanginzel — APPROVED** [review]

**Comment by tilmanginzel** [comment]
By the way, your local git author is not mapped to your Github account. You might want to [configure](https://help.github.com/articles/setting-your-commit-email-address-in-git/) this so commits can be referred to your user. ;)

**Review by tilmanginzel — APPROVED** [review]

**Comment by trietsch** [comment]
Cool, I've updated the license in the readme as well. Yeah, you're correct, my local git author is configured for my work, since I'm working on the laptop provided by my work :)

**Comment by tilmanginzel** [comment]
No worries. You can configure multiple email addresses in your Github profile (which stay hidden), but I could also understand if you don't want to add it.

**Pull request merged**
