### PR TITLE
Use Keyword as input instead of Script Filter

### LINKED ISSUE #1: On/Off switch would be nice
Could you add On and Off states (to save battery when no need for BT).

### PR DESCRIPTION
**Pull request by tilmanginzel**
Hey @trietsch,

would you be so kind and review the following (minor) changes? The info.plist file changed all over the place, but basically this is what's different: 
* `blt-on`, `blt-off` and `blt-toggle` now use the correct input _Keyword_ instead of _Script Filter_. This fixes the weird usability issue mentioned in #1.

Afterwards I'd like to publish version 0.4.0 (version file is already updated in this merge request).

Thanks and cheers
Tilman

### CODE REVIEW

**Comment by trietsch** [comment]
Hey Tilman, I've already changed this in my version, so I think it should be already there as well:
image

But I presume it wasn't?

**Comment by tilmanginzel** [comment]
Yeah I just noticed that this was already changed in the published version, but not reflected in the actual code in the repository. We should make sure that those don't diverge. :/

**Comment by trietsch** [comment]
Ah, that makes sense. Can we "generate" the .alfredworkflow file somehow? Otherwise we just have to keep an eye on that they don't diverge yeah. 
But all in all, looks good to me :)

**Comment by tilmanginzel** [comment]
> Can we "generate" the .alfredworkflow file somehow?

That would be ideal, but I don't know of any possibility to do this. There might be one, but as we don't release so often we can just try to keep an eye on it for now. :)

**Comment by tilmanginzel** [comment]
@trietsch I just published v0.4.0. Update functionality works great! 👍

**Pull request merged**
